apiVersion: v1
kind: Service
metadata:
  name: simple-nodejs-service
spec:
  type: LoadBalancer
  selector:
    app: simple-nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
